#!/bin/bash
#PBS -N RaMViD_train_seg
#PBS -l walltime=64:00:00
#PBS -l select=1:ncpus=4:mem=128gb:ngpus=1:gpu_type=RTX6000
#PBS -e /rds/general/user/xz3622/home/ramvid_seg_error.log
#PBS -o /rds/general/user/xz3622/home/ramvid_seg_output.log

module load cuda/11.4.2
module load cudnn/8.2.4

echo "Modules loaded..."

source $HOME/.bashrc
conda activate ram

echo "Conda environment set..."

cp -r $HOME/Projects/RaMViD $TMPDIR
cp -r $HOME/Projects/uavid_ramvid_seg_rearrange $TMPDIR
export OPENAI_LOGDIR="$HOME/Projects/RaMViD/with_seg_models_rearrange"
# export MASTER_ADDR="localhost"
# echo $MASTER_ADDR

cd $TMPDIR

echo "Current working path:"
echo $(pwd)

echo "Files in the current folder:"
echo $(ls)

echo "Train the model..."

python ./RaMViD/RaMViD/scripts/img_train.py --data_dir ./uavid_ramvid_seg_rearrange/uavid_train --image_size 64 --num_channels 128 --num_res_blocks 3 --scale_time_dim 0 --diffusion_steps 1000 --noise_schedule linear --lr 2e-5 --batch_size 1 --microbatch 1 --seq_len 20 --mask_range 19, --uncondition_rate 0.25 --save_interval 3000 --resume_checkpoint ./RaMViD/with_seg_models_rearrange/model311000.pt

echo "Traning finished..."

echo "Finished"
